### ISSUE TITLE
The History interface does not work as documented

### ISSUE THREAD

**Issue by Lettumika** [appercept/Delphi-WebMocks#53]
If one want's to access history, one must currenly typecast interface for example like
` Assert.AreEqual('/document',  IWebMockHTTPRequest (wm.History.Last).RequestURI);`
in read.me it says `Assert.AreEqual('/document', WebMock.History.Last.RequestURI);` which seems to be outdated.

**Comment by rhatherall** [comment]
I've renamed this issue to reflect the intention of having the history work as per the documentation, not "correct" the documentation. This was an error introduced while refactoring.
