### ISSUE TITLE
Only the first WebMock.Assert in a test yields correct assertion result

### ISSUE THREAD

**Issue by bolligerm** [appercept/Delphi-WebMocks#58]
If a test contains two WebMock.Assert calls, then only the first one yields the correct assertion result. The second one always passes, even if failure would be expected.

Example:

```
// ... Do a HTTP request (with body 'A') ...
WebMock.Assert.Get('/endpoint').WithBody('A').WasRequested;

// ... Do a second identical HTTP request (again with body 'A') ...
WebMock.Assert.Get('/endpoint').WithBody('B').WasRequested;
```
The first WebMock.Assert succeeds, but the second one (that checks for B) also succeeds, even though one would expect it to fail.

**Comment by rhatherall** [comment]
Hi @bolligerm, this has been a known behaviour since the beginning. I typically only write tests with a single assertion, which is why it's not been a high priority to resolve. However, we should support this. A fix is on its way. Thank you for reporting this.

**Comment by bolligerm** [comment]
Thank you, I appreciate the change and the swift reaction!
